---
# We use Cirrus for most of integration tests, because macOS instances of GHA
# are too slow and flaky, and Linux instances of GHA do not support KVM.

# yamllint disable rule:line-length


common_template: &common_template
  timeout_in: 30m
  # We can't use macOS instances of Cirrus because of lack of support for nested VMs.
  # (sysctl machdep.cpu.features lacks "VMX" flag)
  container:
    image: ubuntu:22.04
    kvm: true
    cpu: 2
    memory: 8G
  env:
    DEBIAN_FRONTEND: noninteractive
  info_script:
  - uname -a
  - df -T
  - ls -l /dev/kvm
  - cat /proc/cpuinfo
  install_deps_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ca-certificates curl git golang jq openssh-client make netcat ovmf sudo qemu-system-x86 qemu-utils
  go_cache:
    fingerprint_script: uname -s ; cat go.sum
    folder: /root/go/pkg/mod
  build_script: make
  install_script: make install
  prepare_user_script:
  - groupadd -g $(stat -c '%g' /dev/kvm) kvm
  - useradd -m -G kvm testuser

task:
  <<: *common_template
  env:
    # yamllint disable rule:key-duplicates
    matrix:
      # We only test "Tier 1" yamls. See templates/README.md for the list of the "Tier 1" yamls.
      # default.yaml and vmnet.yaml are tested on GHA macOS.
      TEMPLATE: alpine.yaml
      TEMPLATE: debian.yaml
      TEMPLATE: fedora.yaml
      TEMPLATE: archlinux.yaml
      TEMPLATE: opensuse.yaml
      TEMPLATE: experimental/net-user-v2.yaml
      TEMPLATE: docker.yaml
  lima_cache:
    fingerprint_script: uname -s ; cat templates/$TEMPLATE
    folder: /home/testuser/.cache/lima
  lima_cache_fix_perm_script: chown -R testuser.testuser /home/testuser
  debug_cache_script: sudo -iu testuser $(pwd)/hack/debug-cache.sh
  test_script: sudo -iu testuser $(pwd)/hack/test-templates.sh $(pwd)/templates/$TEMPLATE
  debug_cache2_script: sudo -iu testuser $(pwd)/hack/debug-cache.sh

colima_task:
  <<: *common_template
  colima_install_deps_script:
  - curl -fOSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_24.0.1-1~ubuntu.22.04~jammy_amd64.deb
  - dpkg -i docker-ce-cli_24.0.1-1~ubuntu.22.04~jammy_amd64.deb
  colima_install_script:
  - git clone https://github.com/abiosoft/colima
  - cd colima
  - git checkout v0.5.5
  - make
  - make install
  lima_cache:
    fingerprint_script: uname -s ; colima version
    folder: /home/testuser/.cache/lima
  lima_cache_fix_perm_script: chown -R testuser.testuser /home/testuser
  debug_cache_script: sudo -iu testuser $(pwd)/hack/debug-cache.sh
  test_script: sudo -iu testuser $(pwd)/hack/test-colima.sh
  debug_cache2_script: sudo -iu testuser $(pwd)/hack/debug-cache.sh
