// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go [version omitted for reproducibility]
// 	protoc        [version omitted for reproducibility]
// source: guestservice.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPorts    []*IPPort              `protobuf:"bytes,1,rep,name=local_ports,json=localPorts,proto3" json:"local_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_guestservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetLocalPorts() []*IPPort {
	if x != nil {
		return x.LocalPorts
	}
	return nil
}

type Event struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Time              *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	AddedLocalPorts   []*IPPort              `protobuf:"bytes,2,rep,name=added_local_ports,json=addedLocalPorts,proto3" json:"added_local_ports,omitempty"`
	RemovedLocalPorts []*IPPort              `protobuf:"bytes,3,rep,name=removed_local_ports,json=removedLocalPorts,proto3" json:"removed_local_ports,omitempty"`
	Errors            []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_guestservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetAddedLocalPorts() []*IPPort {
	if x != nil {
		return x.AddedLocalPorts
	}
	return nil
}

func (x *Event) GetRemovedLocalPorts() []*IPPort {
	if x != nil {
		return x.RemovedLocalPorts
	}
	return nil
}

func (x *Event) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type IPPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp, udp
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPPort) Reset() {
	*x = IPPort{}
	mi := &file_guestservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPPort) ProtoMessage() {}

func (x *IPPort) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPPort.ProtoReflect.Descriptor instead.
func (*IPPort) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{2}
}

func (x *IPPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *IPPort) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Inotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPath     string                 `protobuf:"bytes,1,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inotify) Reset() {
	*x = Inotify{}
	mi := &file_guestservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inotify) ProtoMessage() {}

func (x *Inotify) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inotify.ProtoReflect.Descriptor instead.
func (*Inotify) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{3}
}

func (x *Inotify) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *Inotify) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type TunnelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp, udp
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	GuestAddr     string                 `protobuf:"bytes,4,opt,name=guest_addr,json=guestAddr,proto3" json:"guest_addr,omitempty"`
	UdpTargetAddr string                 `protobuf:"bytes,5,opt,name=udp_target_addr,json=udpTargetAddr,proto3" json:"udp_target_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_guestservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TunnelMessage) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TunnelMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TunnelMessage) GetGuestAddr() string {
	if x != nil {
		return x.GuestAddr
	}
	return ""
}

func (x *TunnelMessage) GetUdpTargetAddr() string {
	if x != nil {
		return x.UdpTargetAddr
	}
	return ""
}

type TimeSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=host_time,json=hostTime,proto3" json:"host_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	mi := &file_guestservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{5}
}

func (x *TimeSyncRequest) GetHostTime() *timestamppb.Timestamp {
	if x != nil {
		return x.HostTime
	}
	return nil
}

type TimeSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adjusted      bool                   `protobuf:"varint,1,opt,name=adjusted,proto3" json:"adjusted,omitempty"`
	DriftMs       int64                  `protobuf:"varint,2,opt,name=drift_ms,json=driftMs,proto3" json:"drift_ms,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncResponse) Reset() {
	*x = TimeSyncResponse{}
	mi := &file_guestservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncResponse) ProtoMessage() {}

func (x *TimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guestservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncResponse.ProtoReflect.Descriptor instead.
func (*TimeSyncResponse) Descriptor() ([]byte, []int) {
	return file_guestservice_proto_rawDescGZIP(), []int{6}
}

func (x *TimeSyncResponse) GetAdjusted() bool {
	if x != nil {
		return x.Adjusted
	}
	return false
}

func (x *TimeSyncResponse) GetDriftMs() int64 {
	if x != nil {
		return x.DriftMs
	}
	return 0
}

func (x *TimeSyncResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_guestservice_proto protoreflect.FileDescriptor

const file_guestservice_proto_rawDesc = "" +
	"\n" +
	"\x12guestservice.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x04Info\x12(\n" +
	"\vlocal_ports\x18\x01 \x03(\v2\a.IPPortR\n" +
	"localPorts\"\xbd\x01\n" +
	"\x05Event\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x123\n" +
	"\x11added_local_ports\x18\x02 \x03(\v2\a.IPPortR\x0faddedLocalPorts\x127\n" +
	"\x13removed_local_ports\x18\x03 \x03(\v2\a.IPPortR\x11removedLocalPorts\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"H\n" +
	"\x06IPPort\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"X\n" +
	"\aInotify\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x01 \x01(\tR\tmountPath\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x96\x01\n" +
	"\rTunnelMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"guest_addr\x18\x04 \x01(\tR\tguestAddr\x12&\n" +
	"\x0fudp_target_addr\x18\x05 \x01(\tR\rudpTargetAddr\"J\n" +
	"\x0fTimeSyncRequest\x127\n" +
	"\thost_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bhostTime\"_\n" +
	"\x10TimeSyncResponse\x12\x1a\n" +
	"\badjusted\x18\x01 \x01(\bR\badjusted\x12\x19\n" +
	"\bdrift_ms\x18\x02 \x01(\x03R\adriftMs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xf9\x01\n" +
	"\fGuestService\x12(\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a\x05.Info\x12-\n" +
	"\tGetEvents\x12\x16.google.protobuf.Empty\x1a\x06.Event0\x01\x121\n" +
	"\vPostInotify\x12\b.Inotify\x1a\x16.google.protobuf.Empty(\x01\x12,\n" +
	"\x06Tunnel\x12\x0e.TunnelMessage\x1a\x0e.TunnelMessage(\x010\x01\x12/\n" +
	"\bSyncTime\x12\x10.TimeSyncRequest\x1a\x11.TimeSyncResponseB/Z-github.com/lima-vm/lima/v2/pkg/guestagent/apib\x06proto3"

var (
	file_guestservice_proto_rawDescOnce sync.Once
	file_guestservice_proto_rawDescData []byte
)

func file_guestservice_proto_rawDescGZIP() []byte {
	file_guestservice_proto_rawDescOnce.Do(func() {
		file_guestservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guestservice_proto_rawDesc), len(file_guestservice_proto_rawDesc)))
	})
	return file_guestservice_proto_rawDescData
}

var file_guestservice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_guestservice_proto_goTypes = []any{
	(*Info)(nil),                  // 0: Info
	(*Event)(nil),                 // 1: Event
	(*IPPort)(nil),                // 2: IPPort
	(*Inotify)(nil),               // 3: Inotify
	(*TunnelMessage)(nil),         // 4: TunnelMessage
	(*TimeSyncRequest)(nil),       // 5: TimeSyncRequest
	(*TimeSyncResponse)(nil),      // 6: TimeSyncResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_guestservice_proto_depIdxs = []int32{
	2,  // 0: Info.local_ports:type_name -> IPPort
	7,  // 1: Event.time:type_name -> google.protobuf.Timestamp
	2,  // 2: Event.added_local_ports:type_name -> IPPort
	2,  // 3: Event.removed_local_ports:type_name -> IPPort
	7,  // 4: Inotify.time:type_name -> google.protobuf.Timestamp
	7,  // 5: TimeSyncRequest.host_time:type_name -> google.protobuf.Timestamp
	8,  // 6: GuestService.GetInfo:input_type -> google.protobuf.Empty
	8,  // 7: GuestService.GetEvents:input_type -> google.protobuf.Empty
	3,  // 8: GuestService.PostInotify:input_type -> Inotify
	4,  // 9: GuestService.Tunnel:input_type -> TunnelMessage
	5,  // 10: GuestService.SyncTime:input_type -> TimeSyncRequest
	0,  // 11: GuestService.GetInfo:output_type -> Info
	1,  // 12: GuestService.GetEvents:output_type -> Event
	8,  // 13: GuestService.PostInotify:output_type -> google.protobuf.Empty
	4,  // 14: GuestService.Tunnel:output_type -> TunnelMessage
	6,  // 15: GuestService.SyncTime:output_type -> TimeSyncResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_guestservice_proto_init() }
func file_guestservice_proto_init() {
	if File_guestservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guestservice_proto_rawDesc), len(file_guestservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guestservice_proto_goTypes,
		DependencyIndexes: file_guestservice_proto_depIdxs,
		MessageInfos:      file_guestservice_proto_msgTypes,
	}.Build()
	File_guestservice_proto = out.File
	file_guestservice_proto_goTypes = nil
	file_guestservice_proto_depIdxs = nil
}
