// SPDX-FileCopyrightText: Copyright The Lima Authors
// SPDX-License-Identifier: Apache-2.0

package networks

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"slices"
	"strings"

	"github.com/sirupsen/logrus"
)

func Sudoers() (string, error) {
	cfg, err := LoadConfig()
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	if runtime.GOOS == "darwin" {
		// On Linux, lima-net creates the varRun directory itself.
		fmt.Fprintf(&sb, "%%%s ALL=(root:wheel) NOPASSWD:NOSETENV: %s\n", cfg.Group, cfg.MkdirCmd())
	}

	// names must be in stable order to be able to check if sudoers file needs updating
	names := make([]string, 0, len(cfg.Networks))
	for name, nw := range cfg.Networks {
		if nw.Mode == ModeUserV2 {
			continue // no sudo needed
		}
		names = append(names, name)
	}
	slices.Sort(names)

	for _, name := range names {
		sb.WriteRune('\n')
		fmt.Fprintf(&sb, "# Manage %q network daemons\n", name)
		for _, daemon := range RequiredDaemons() {
			if ok, err := cfg.IsDaemonInstalled(daemon); err != nil {
				return "", err
			} else if !ok {
				continue
			}
			user, err := cfg.User(daemon)
			if err != nil {
				return "", err
			}
			cmds := []string{cfg.StartCmd(name, daemon), cfg.StopCmd(name, daemon)}
			if daemon == LimaNet {
				// One tap device per instance is attached to the bridge; the
				// wildcard only matches the names generated by TapName.
				cmds = append(cmds, cfg.TapCmd(name, TapNamePattern()))
			}
			sb.WriteRune('\n')
			fmt.Fprintf(&sb, "%%%s ALL=(%s:%s) NOPASSWD:NOSETENV: \\\n", cfg.Group, user.User, user.Group)
			fmt.Fprintf(&sb, "    %s\n", strings.Join(cmds, ", \\\n    "))
		}
	}
	return strings.TrimPrefix(sb.String(), "\n"), nil
}

func (c *Config) passwordLessSudo(ctx context.Context) error {
	// Flush cached sudo password
	cmd := exec.CommandContext(ctx, "sudo", "-k")
	logrus.Infof("Running: %v", cmd.Args)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to run %v: %w", cmd.Args, err)
	}
	// Verify that user/groups for every daemon work without a password, e.g.
	// %admin ALL = (ALL:ALL) NOPASSWD: ALL
	for _, daemon := range RequiredDaemons() {
		if ok, err := c.IsDaemonInstalled(daemon); err != nil {
			return err
		} else if !ok {
			continue
		}
		user, err := c.User(daemon)
		if err != nil {
			return err
		}
		cmd = exec.CommandContext(ctx, "sudo", "--user", user.User, "--group", user.Group, "--non-interactive", "true")
		logrus.Infof("Running: %v", cmd.Args)
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("failed to run %v: %w", cmd.Args, err)
		}
	}
	return nil
}

func (c *Config) VerifySudoAccess(ctx context.Context, sudoersFile string) error {
	if sudoersFile == "" {
		err := c.passwordLessSudo(ctx)
		if err == nil {
			logrus.Debug("sudo doesn't seem to require a password")
			return nil
		}
		return fmt.Errorf("passwordLessSudo error: %w", err)
	}
	hint := fmt.Sprintf("run `%s sudoers >etc_sudoers.d_lima && sudo install -o root etc_sudoers.d_lima %q`)",
		os.Args[0], sudoersFile)
	b, err := os.ReadFile(sudoersFile)
	if err != nil {
		// /etc/sudoers.d is typically 0750 root:root, so the file can't be read here
		// even when it was installed correctly; the sudo invocation would fail loudly
		// later if it wasn't.
		if errors.Is(err, os.ErrPermission) {
			logrus.Debugf("can't read %#q to verify its contents: %s", sudoersFile, err)
			return nil
		}
		// Default networks.yaml specifies /etc/sudoers.d/lima file. Don't throw an error when the
		// file doesn't exist, as long as password-less sudo still works.
		if errors.Is(err, os.ErrNotExist) {
			err = c.passwordLessSudo(ctx)
			if err == nil {
				logrus.Debugf("%#q does not exist, but sudo doesn't seem to require a password", sudoersFile)
				return nil
			}
			logrus.Debugf("%#q does not exist; passwordLessSudo error: %s", sudoersFile, err)
		}
		return fmt.Errorf("can't read %#q: %w: (Hint: %s)", sudoersFile, err, hint)
	}
	sudoers, err := Sudoers()
	if err != nil {
		return err
	}
	if string(b) != sudoers {
		// Happens on upgrading socket_vmnet with Homebrew
		return fmt.Errorf("sudoers file %#q is out of sync and must be regenerated (Hint: %s)", sudoersFile, hint)
	}
	return nil
}
