// SPDX-FileCopyrightText: Copyright The Lima Authors
// SPDX-License-Identifier: Apache-2.0

package networks

import (
	"context"
	"fmt"
	"os"
	"runtime"
	"slices"
	"strings"

	"github.com/sirupsen/logrus"

	"github.com/lima-vm/lima/v2/pkg/sudoers"
)

func (c Config) Sudoers() (string, error) {
	var sb strings.Builder
	if runtime.GOOS == "darwin" {
		// On Linux, lima-privileged-net creates the varRun directory itself.
		sb.WriteString(sudoers.NOPASSWD("%"+c.Group, "root", "wheel", c.MkdirCmd()))
	}

	// names must be in stable order to be able to check if sudoers file needs updating
	names := make([]string, 0, len(c.Networks))
	for name, nw := range c.Networks {
		if nw.Mode == ModeUserV2 {
			continue // no sudo needed
		}
		names = append(names, name)
	}
	slices.Sort(names)

	for _, name := range names {
		sb.WriteRune('\n')
		fmt.Fprintf(&sb, "# Manage %q network daemons\n", name)
		for _, daemon := range RequiredDaemons() {
			if ok, err := c.IsDaemonInstalled(daemon); err != nil {
				return "", err
			} else if !ok {
				continue
			}
			user, err := c.User(daemon)
			if err != nil {
				return "", err
			}
			cmds := []string{c.StartCmd(name, daemon)}
			if daemon == LimaPrivilegedNet {
				// One tap device per instance is attached to the bridge; the
				// wildcard only matches the names generated by TapName.
				cmds = append(cmds, c.TapCmdPattern(name))
				path, err := c.DaemonPath(daemon)
				if err != nil {
					return "", err
				}
				if cmds, err = sudoers.Pin(path, cmds...); err != nil {
					return "", err
				}
			}
			// Not pinned: a system binary, updated independently of Lima.
			cmds = append(cmds, c.StopCmd(name, daemon))
			sb.WriteRune('\n')
			sb.WriteString(sudoers.NOPASSWD("%"+c.Group, user.User, user.Group, cmds...))
		}
	}
	return strings.TrimPrefix(sb.String(), "\n"), nil
}

// runAs lists the identities the generated grants are exercised as.
func (c *Config) runAs() ([]sudoers.RunAs, error) {
	var runAs []sudoers.RunAs
	for _, daemon := range RequiredDaemons() {
		if ok, err := c.IsDaemonInstalled(daemon); err != nil {
			return nil, err
		} else if !ok {
			continue
		}
		user, err := c.User(daemon)
		if err != nil {
			return nil, err
		}
		runAs = append(runAs, sudoers.RunAs{User: user.User, Group: user.Group})
	}
	return runAs, nil
}

func (c *Config) VerifySudoAccess(ctx context.Context, sudoersFile string) error {
	runAs, err := c.runAs()
	if err != nil {
		return err
	}
	if sudoersFile == "" {
		if err := sudoers.VerifyPasswordLess(ctx, runAs...); err != nil {
			return fmt.Errorf("sudo seems to require a password: %w", err)
		}
		logrus.Debug("sudo doesn't seem to require a password")
		return nil
	}
	fragment, err := c.Sudoers()
	if err != nil {
		return err
	}
	hint := sudoers.RegenerateHint(os.Args[0], sudoersFile, nil)
	return sudoers.VerifyFragment(ctx, sudoersFile, fragment, hint, runAs...)
}
