// SPDX-FileCopyrightText: Copyright The Lima Authors
// SPDX-License-Identifier: Apache-2.0

package asifutil

import (
	"testing"

	"gotest.tools/v3/assert"
)

func TestParseDiskutilImageAttachOutput(t *testing.T) {
	const input = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>system-entities</key>
	<array>
		<dict>
			<key>content-hint</key>
			<string>GUID_partition_scheme</string>
			<key>dev-entry</key>
			<string>disk4</string>
			<key>size</key>
			<integer>107374182400</integer>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_ISC</string>
			<key>dev-entry</key>
			<string>disk4s1</string>
			<key>size</key>
			<integer>524288000</integer>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Container</string>
			<key>dev-entry</key>
			<string>disk5</string>
			<key>size</key>
			<integer>524288000</integer>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk5s1</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Preboot</string>
			<key>size</key>
			<integer>524288000</integer>
			<key>volume-name</key>
			<string>iSCPreboot</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk5s2</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>XART</string>
			<key>size</key>
			<integer>524288000</integer>
			<key>volume-name</key>
			<string>xART</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk5s3</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Hardware</string>
			<key>size</key>
			<integer>524288000</integer>
			<key>volume-name</key>
			<string>Hardware</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk5s4</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Recovery</string>
			<key>size</key>
			<integer>524288000</integer>
			<key>volume-name</key>
			<string>Recovery</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS</string>
			<key>dev-entry</key>
			<string>disk4s2</string>
			<key>size</key>
			<integer>101481185280</integer>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Container</string>
			<key>dev-entry</key>
			<string>disk7</string>
			<key>size</key>
			<integer>101481185280</integer>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk7s1</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>System</string>
			<key>size</key>
			<integer>101481185280</integer>
			<key>volume-group</key>
			<string>4B262719-EFC8-4B4D-8831-8AD57E005B59</string>
			<key>volume-name</key>
			<string>Macintosh HD</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk7s2</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Preboot</string>
			<key>size</key>
			<integer>101481185280</integer>
			<key>volume-name</key>
			<string>Preboot</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk7s3</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Recovery</string>
			<key>size</key>
			<integer>101481185280</integer>
			<key>volume-name</key>
			<string>Recovery</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk7s4</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Update</string>
			<key>size</key>
			<integer>101481185280</integer>
			<key>volume-name</key>
			<string>Update</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk7s5</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Data</string>
			<key>size</key>
			<integer>101481185280</integer>
			<key>volume-group</key>
			<string>4B262719-EFC8-4B4D-8831-8AD57E005B59</string>
			<key>volume-name</key>
			<string>Data</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk7s6</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>VM</string>
			<key>size</key>
			<integer>101481185280</integer>
			<key>volume-name</key>
			<string>VM</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Recovery</string>
			<key>dev-entry</key>
			<string>disk4s3</string>
			<key>size</key>
			<integer>5368668160</integer>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Container</string>
			<key>dev-entry</key>
			<string>disk6</string>
			<key>size</key>
			<integer>5368668160</integer>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk6s1</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Recovery</string>
			<key>size</key>
			<integer>5368668160</integer>
			<key>volume-name</key>
			<string>Recovery</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_APFS_Volume</string>
			<key>dev-entry</key>
			<string>disk6s2</string>
			<key>filesystem-name</key>
			<string>APFS</string>
			<key>filesystem-type</key>
			<string>apfs</string>
			<key>role</key>
			<string>Update</string>
			<key>size</key>
			<integer>5368668160</integer>
			<key>volume-name</key>
			<string>Update</string>
		</dict>
	</array>
</dict>
</plist>
`
	expected := &AttachedDisk{
		Data: "disk7s5",
	}
	res, err := parseDiskutilImageAttachOutput(input)
	assert.NilError(t, err)
	assert.DeepEqual(t, res, expected)
}
