name: Automated Link Health Check
on:
  workflow_dispatch:
  schedule:
  - cron: "00 18 * * *" # Runs the cron at 1800 hrs UTC Everyday
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332 # v2.4.1
      with:
        fail: false
        output: ./lychee/out.md
    - name: Create Issue From File
      if: steps.lychee.outputs.exit_code != 0
      uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5.0.1
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
        labels: report, automated issue
